// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBegGCEOms_BG0tPxoXVfUzNPjjEctsb98',
    appId: '1:1027001585310:web:3c226b43c2e6106333758f',
    messagingSenderId: '1027001585310',
    projectId: 'bazaar-ak',
    authDomain: 'bazaar-ak.firebaseapp.com',
    storageBucket: 'bazaar-ak.firebasestorage.app',
    measurementId: 'G-XX3S9Y82SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtXxpNQdafbx4urKpORzIohAU3ELtHQ_E',
    appId: '1:1027001585310:android:d6a804606e8192b433758f',
    messagingSenderId: '1027001585310',
    projectId: 'bazaar-ak',
    storageBucket: 'bazaar-ak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BHcBT5LTeJ50egE0cqrv6cHlaJnuGV4',
    appId: '1:1027001585310:ios:51a030a5692290f633758f',
    messagingSenderId: '1027001585310',
    projectId: 'bazaar-ak',
    storageBucket: 'bazaar-ak.firebasestorage.app',
    androidClientId: '1027001585310-gs6id2v45k9p9rbo4sc25goo40ks27ml.apps.googleusercontent.com',
    iosClientId: '1027001585310-ke3u8lvb73l6dnnf3tevaif6jm3lj0gu.apps.googleusercontent.com',
    iosBundleId: 'com.bazaar.ak.bazaarAk',
  );

}